import Head from 'next/head'
import Header from "../components/header";
import Footer from "../components/footer";

export default function Home() {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="bg-gray-200">
        
      </main>
      <Footer />

    </section>
  )
}
