const blogReducersName: {
  SET_ARTICLES: "SET_ARTICLES";
  SET_ACTUAL_ARTICLES: "SET_ACTUAL_ARTICLES";
  SET_PAGE_ARTICLE_LENGTH: "SET_PAGE_ARTICLE_LENGTH";
  SET_ACTUAL_ARTICLE: "SET_ACTUAL_ARTICLE";
  SET_ACTUAL_PAGE_INDEX: "SET_ACTUAL_PAGE_INDEX";
} = {
  SET_ARTICLES: "SET_ARTICLES",
  SET_ACTUAL_ARTICLES: "SET_ACTUAL_ARTICLES",
  SET_PAGE_ARTICLE_LENGTH: "SET_PAGE_ARTICLE_LENGTH",
  SET_ACTUAL_ARTICLE: "SET_ACTUAL_ARTICLE",
  SET_ACTUAL_PAGE_INDEX: "SET_ACTUAL_PAGE_INDEX",
};

export { blogReducersName };
